######################### ROS STUFF #########################
export HOST=jetauto_1
export MACHINE_TYPE=jetauto_omni
export LIDAR_TYPE=A1
export PROJECTPATH=~/source
source /opt/ros/noetic/setup.bash
source $PROJECTPATH/ORB_SLAM3/Examples_old/ROS/ORB_SLAM3/build/devel/setup.bash
export ROS_PACKAGE_PATH=$PROJECTPATH/ORB_SLAM3/Examples_old/ROS:${ROS_PACKAGE_PATH}
export GAZEBO_MODEL_PATH=/usr/share/gazebo-9/models/:${GAZEBO_MODEL_PATH}
export GAZEBO_MODEL_PATH=$PROJECTPATH/SLAM_Sim/catkin_ws/src/jetauto_arena/models:${GAZEBO_MODEL_PATH}
source $PROJECTPATH/SLAM_Sim/catkin_ws/devel/setup.bash 
#############################################################